
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy the app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    - name: Install modules
      run: npm install
    - name: Manually change the config file
      run: echo 'export const settings = { host:"http://localhost:3030" };' > src/config.js
    - name: Build front-end
      run: npm run start-fe &
    - name: Build back-end
      run: npm run server-be &
    - name: Install browsers
      run: npx playwright install
    - name: Run tests
      run: npm test

  deploy_be:
    needs: build_test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.BE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: 
      
  deploy_fe:
    needs: deploy_be
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.FE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true